### ISSUE TITLE
pure VS impure functions

### ISSUE THREAD

**Issue by mossa-Sammer** [GSG-G8/LMAR_Express#45]
https://github.com/GSG-G8/LMAR_Express/blob/c03401ca06d9822e20194b5f26102fe494196ff5/script/logic.js#L18-L22
your goal here to find an element in an array, so you don't have to return a new array contains only the desired item, also the ```array.filter``` method iterate through the whole array.
maybe it would be better if you used the ```array.find``` method because it just returns the first matching element,
read about it here in mdn
[array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

**Comment by mFlaifel** [comment]
hi Mossa,
thank you for your kindly revision.
in this function we use contains because there are some keywords is shared between multiple products, so the expected search result some times contains more than one element.

**Comment by Asmaathabet** [comment]
@mFlaifel  I agree in using filter function for displaying many items during the search 
:+1:
